name: PR Release

on:
  pull_request:

jobs:
  pr-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Uncomment this if you're using pnpm
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm # or pnpm

      - name: Install Dependencies
        run: npm ci # or pnpm install

      - name: Build
        run: npm build # or pnpm build

      - name: Publish
        uses: kotarella1110/pr-voyager@v0
        with:
          publish: npm publish # or pnpm publish -r
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}